# * If you wish to use webgpu backend, create a .cargo/config.toml in the root of the repo containing:
[build]
rustflags = [ "--cfg=web_sys_unstable_apis" ]
rustdocflags = [ "--cfg=web_sys_unstable_apis" ]
# * If you wish to disable webgpu backend and instead use webgl backend, change your wgpu Cargo.toml entry to:
# wgpu = { version = "", default-features = false, features = ["webgl"] }
